name: CI/CD for deploying income-management-service on azure cloud
on:
  push:
    branches: [ main ]

jobs:
  build-and-push-on-azure-docker-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/docker-login@v1
        with:
          login-server: jagwaniazuredockerregistry.azurecr.io
          username: ${{ secrets.AZURE_DOCKER_REGISTRY_USER }}
          password: ${{ secrets.AZURE_DOCKER_REGISTRY_PWD }}
      - run: |
          ./gradlew clean jib
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: jagwani-azure-resource-group
          dns-name-label: azure-demo
          image: jagwaniazuredockerregistry.azurecr.io/income-management-service:latest
          registry-username: ${{ secrets.AZURE_DOCKER_REGISTRY_USER }}
          registry-password: ${{ secrets.AZURE_DOCKER_REGISTRY_PWD }}
          name: incomemanagementcontainer
          ports: 8099, 9099
          location: 'centralus'
